print("Create and access elements of tuple")
my_tuple=(10,20,30,40,50)
print("created tuple:",my_tuple)
print("\n access elements in tuple")
print("accessing elements at index 3:",my_tuple[3])
print("accessing element at index 4:",my_tuple[4])
print("slicing the tuple from index 0 to 3",my_tuple[0:4])
print("\n nested tuple")
nested_tuple=(1,2,(3,4,5),6,7)
print("nested tuple:",nested_tuple)
print("accessing element of the inner tuple:",nested_tuple[2][0])
print("\n Repeition of tuples")
repeated_tuple=my_tuple*2
print("repeated tuple:",repeated_tuple)
