print("create and access list elements")
my_list=['a','b','c','d','e']
print("created list:", my_list)
print("\n Accessing element at index 1")
print(my_list[1])
print("Accessing element at index 3")
print(my_list[3])
print("Add and Remove elements")
print("\n Adding element")
my_list.append('f')
print("New list:",my_list)
print("\n Removing element")
my_list.remove('b')
print("New list:",my_list)
print("\n Sorting elements")
my_list.sort()
print("Sorted elements in ascending order:",my_list)
my_list.sort(reverse=True)
print("Sorted elements in descending order:",my_list)